site_name: PPP Coding Standards
nav:
  - About: index.md
  - Fields/Variables: fields-variables.md
  - Properties: properties.md
  - Methods: methods.md
  - Naming Conventions: naming.md
  - Namespaces: namespaces.md
  - Optimization Techniques: optimization-techniques.md
theme: readthedocs