site_name: PPP Coding Standards
copyright: Copyright © 2020 - 2022 Pie On A Plate Productions LLC
nav:
  - About: index.md
  - Fields/Variables: fields-variables.md
  - Properties: properties.md
  - Methods: methods.md
  - Naming Conventions: naming.md
  - Namespaces: namespaces.md
  - Optimization Techniques: optimization-techniques.md
  - Code File Structure: code-file-structure.md
  - Other: other.md
theme: 
  name: readthedocs
  custom_dir: overrides
plugins:
- search
- git-revision-date-localized